// admin-front/admin-app/src/app/components/invalidate-certificate-dialog/invalidate-certificate-dialog.component.ts
import { Component, Inject, OnInit } from '@angular/core';
import { MatDialog, MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { CertificateDTO } from 'src/app/models/CertificateDTO';
import { CertificateService } from 'src/app/services/certificate.service';
import { SnackBarService } from 'src/app/services/snack-bar.service';
import { CertificateDialogComponent } from '../certificate-dialog/certificate-dialog.component';

@Component({
  selector: 'app-invalidate-certificate-dialog',
  templateUrl: './invalidate-certificate-dialog.component.html',
  styleUrls: ['./invalidate-certificate-dialog.component.scss']
})
export class InvalidateCertificateDialogComponent implements OnInit {

  reasons: string[] = [
    "Loss of a private key corresponding to the public key on the certificate",
    "Unintentional issuance of a certificate as a result of an error or attack on a certification body",
    "Improper conduct of the owner of the issued certificate",
    "Detection of defects in the application for a certificate subsequently",
  ]

  reason: string = "";

  constructor(
    public dialog: MatDialog,
    public dialogRef: MatDialogRef<CertificateDialogComponent>,
    public certificateService: CertificateService,
    public snackBarService: SnackBarService,
    @Inject(MAT_DIALOG_DATA) public selectedAlias: string
  ) { }

  ngOnInit(): void { }

  invalidateCertificate() {
    if (this.reason === "") {
      this.snackBarService.openSnackBar("You need to enter reason of invalidation.")
      return;
    }
    let revokedCertificateDTO = {
      alias: this.selectedAlias,
      reason: this.reason,
    };
    this.certificateService.invalidateCertificate(revokedCertificateDTO).subscribe(
      (response) => {
        this.snackBarService.openSnackBar(response.body as string);
        this.dialogRef.close();
      },
      (error) => {
        this.snackBarService.openSnackBar(error.error as string);
        this.dialogRef.close();  
      }
    );
  }

  setReason(reason: string) {
    this.reason = reason;
  }

}

<div>
    <h4 style="margin-bottom: 2%;">Possible reasons:</h4>
    <ul>
        <li *ngFor="let reasonString of reasons" (click)="setReason(reasonString)"
            style="cursor: pointer; margin-bottom: 2%">
            {{ reasonString }}
        </li>
    </ul>
    <div class="form-floating mb-3">
        <input type="text" class="form-control" id="floatingInput" [(ngModel)]="reason" />
        <label for="floatingInput">Reason</label>
    </div>
    <button class="btn command-button" (click)="invalidateCertificate()">Invalidate</button>
</div>

// admin-front/admin-app/src/components/InvalidateCertificateDialog.vue
<template>
  <div>
    <el-dialog
      title="Invalidate certificate"
      :visible.sync="centerDialogVisible"
      width="40%"
      center
    >
      <h4>Possible reasons:</h4>
      <ul>
        <li
          v-for="reasonItem in reasons"
          :key="reasonItem"
          @click="setReason(reasonItem)"
          style="cursor: pointer"
        >
          {{ reasonItem }}
        </li>
      </ul>
      <div class="form-floating mb-3">
        <input
          type="text"
          class="form-control"
          id="floatingInput"
          v-model="reason"
        />
        <label for="floatingInput">Reason</label>
      </div>
      <span>
        <el-button class="command-button" @click="closeModal"
          >Invalidate</el-button
        >
      </span>
    </el-dialog>
  </div>
</template>

<script>
export default {
  props: ["certificates"],
  data() {
    return {
      reasons: [
        "Loss of a private key corresponding to the public key on the certificate",
        "Unintentional issuance of a certificate as a result of an error or attack on a certification body",
        "Improper conduct of the owner of the issued certificate",
        "Detection of defects in the application for a certificate subsequently",
      ],
      centerDialogVisible: false,
      reason: "",
    };
  },
  methods: {
    closeModal: function () {
      this.centerDialogVisible = false;
      this.$emit("closed", this.reason);
    },
    openModal: function () {
      this.reason = "";
      this.centerDialogVisible = true;
    },
    setReason(reasonItem) {
      this.reason = reasonItem;
    },
  },
};
</script>
<style scoped>
.command-button {
  margin-top: 1%;
  background-color: rgb(22, 117, 90);
  color: white;
}

.command-button:hover {
  background-color: rgb(146, 142, 142);
  color: rgb(0, 0, 0);
}
</style>
