// admin-front/admin-app/src/app/components/key-usage/key-usage.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { KeyUsageDTO } from 'src/app/models/KeyUsageDTO';

@Component({
  selector: 'app-key-usage',
  templateUrl: './key-usage.component.html',
  styleUrls: ['./key-usage.component.scss']
})
export class KeyUsageComponent implements OnInit {

  @Input()
  keyUsage!: KeyUsageDTO;

  constructor() {}

  ngOnInit(): void {}

}

<div class="container center">
    <h4>Key usage</h4>

    <div class="row">
        <div class="col">
            <input [(ngModel)]="keyUsage.certificateSigning" class="form-check-input" type="checkbox" value="" id="certificateSigning">
            <label class="form-check-label" for="certificateSigning">
                Certificate Signing
            </label>
        </div>
        <div class="col">
            <input [(ngModel)]="keyUsage.crlSign" class="form-check-input" type="checkbox" value="" id="crlSign">
            <label class="form-check-label" for="crlSign">
                Crl Signing
            </label>
        </div>
        <div class="col">
            <input [(ngModel)]="keyUsage.dataEncipherment" class="form-check-input" type="checkbox" value="" id="dataEncipherment">
            <label class="form-check-label" for="dataEncipherment">
                Data encipherment
            </label>
        </div>
    </div>
    
    <div class="row">
        <div class="col">
            <input [(ngModel)]="keyUsage.decipherOnly" class="form-check-input" type="checkbox" value="" id="decipherOnly">
            <label class="form-check-label" for="decipherOnly">
                Decipher only
            </label>
        </div>
        <div class="col">
            <input [(ngModel)]="keyUsage.digitalSignature" class="form-check-input" type="checkbox" value="" id="digitalSignature">
            <label class="form-check-label" for="digitalSignature">
                Digital signature
            </label>
        </div>
        <div class="col">
            <input [(ngModel)]="keyUsage.encipherOnly" class="form-check-input" type="checkbox" value="" id="encipherOnly">
            <label class="form-check-label" for="encipherOnly">
                Encipher only
            </label>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <input [(ngModel)]="keyUsage.keyAgreement" class="form-check-input" type="checkbox" value="" id="keyAgreement">
            <label class="form-check-label" for="keyAgreement">
                Key agreement
            </label>
        </div>
        <div class="col">
            <input [(ngModel)]="keyUsage.keyEncipherment" class="form-check-input" type="checkbox" value="" id="keyEncipherment">
            <label class="form-check-label" for="keyEncipherment">
                Key encipherment 
            </label>
        </div>
        <div class="col">
            <input [(ngModel)]="keyUsage.nonRepudiation" class="form-check-input" type="checkbox" value="" id="nonRepudiation">
            <label class="form-check-label" for="nonRepudiation">
                Non repudiation
            </label>
        </div>
    </div>
</div>

// admin-front/admin-app/src/components/KeyUsageComponent.vue
<template>
  <div class="row">
    <h4 id="title-label">Key usage</h4>
    <div class="col-4">
      <form>
        <vue-form-generator
          :schema="schema1"
          :model="model"
          :options="formOptions"
        >
        </vue-form-generator>
      </form>
    </div>
    <div class="col-4">
      <form>
        <vue-form-generator
          :schema="schema2"
          :model="model"
          :options="formOptions"
        >
        </vue-form-generator>
      </form>
    </div>
    <div class="col-4">
      <form>
        <vue-form-generator
          :schema="schema3"
          :model="model"
          :options="formOptions"
        >
        </vue-form-generator>
      </form>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      model: {
        certificateSigning: true,
        crlSign: true,
        dataEncipherment: false,
        decipherOnly: false,
        digitalSignature: false,
        encipherOnly: false,
        keyAgreement: false,
        keyEncipherment: false,
        nonRepudiation: false,
      },

      schema1: {
        groups: [
          {
            styleClasses: "firstCol",
            fields: [
              {
                type: "checkbox",
                label: "Certificate Signing",
                model: "certificateSigning",
              },
              {
                type: "checkbox",
                label: "CRL Sign",
                model: "crlSign",
              },
              {
                type: "checkbox",
                label: "Data Encipherment",
                model: "dataEncipherment",
              },
            ],
          },
        ],
      },
      schema2: {
        groups: [
          {
            styleClasses: "secondCol",
            fields: [
              {
                type: "checkbox",
                label: "Decipher Only",
                model: "decipherOnly",
              },
              {
                type: "checkbox",
                label: "Digital Signature",
                model: "digitalSignature",
              },
              {
                type: "checkbox",
                label: "Encipher Only",
                model: "encipherOnly",
              },
            ],
          },
        ],
      },
      schema3: {
        groups: [
          {
            styleClasses: "thirdCol",
            fields: [
              {
                type: "checkbox",
                label: "Key Agreement",
                model: "keyAgreement",
              },
              {
                type: "checkbox",
                label: "Key Encipherment",
                model: "keyEncipherment",
              },
              {
                type: "checkbox",
                label: "Non Repudiation",
                model: "nonRepudiation",
              },
            ],
          },
        ],
      },
      formOptions: {
        validateAfterLoad: false,
        validateAfterChanged: true,
        validateAsync: true,
      },
    };
  },
};
</script>

<style>
#title-label {
  margin-top: 2%;
  margin-bottom: 2%;
}
</style>
