// admin-front-ng/admin-app/src/app/pages/all-certificates-view/all-certificates-view.component.ts
import { Component, OnInit } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { CertificateDialogComponent } from 'src/app/components/certificate-dialog/certificate-dialog.component';
import { InvalidateCertificateDialogComponent } from 'src/app/components/invalidate-certificate-dialog/invalidate-certificate-dialog.component';
import { CertificateDTO } from 'src/app/models/CertificateDTO';
import { CertificateService } from 'src/app/services/certificate.service';
import { SnackBarService } from 'src/app/services/snack-bar.service';

@Component({
  selector: 'app-all-certificates-view',
  templateUrl: './all-certificates-view.component.html',
  styleUrls: ['./all-certificates-view.component.scss']
})
export class AllCertificatesViewComponent implements OnInit {

  aliases: string[] = [];
  invalidAlias: string = "----------";
  selectedAlias: string = "----------";
  selectedCertificates: CertificateDTO[] = [];
  showModal: boolean = false;

  constructor(public dialog: MatDialog, private certificateService: CertificateService,
    private snackBarService: SnackBarService) { }

  ngOnInit(): void {
    this.certificateService.getAliases()
      .subscribe((response) => {
        this.aliases = [this.invalidAlias];
        this.aliases = [...this.aliases, ...response.body as string[]];
      })
  }

  changeAlias() {
    this.certificateService.getCertificate(this.selectedAlias)
      .subscribe((response) => {
        this.selectedCertificates = response.body as CertificateDTO[];
      });
  }

  checkCertificate() {
    if (this.selectedAlias === this.invalidAlias) {
      this.snackBarService.openSnackBar("Certificate not selected!");
    } else {
      this.certificateService.checkCertificate(this.selectedAlias)
        .subscribe(
          (response) => {
            this.snackBarService.openSnackBar(response.body as string);
          },
          (error) => {
            this.snackBarService.openSnackBar(error.error as string);
          });
    }
  }

  invalidateCertificate(reason: string) {
    if (this.selectedAlias === this.invalidAlias) {
      this.snackBarService.openSnackBar("Certificate not selected!");
    } else {
      let revokedCertificateDTO = {
        alias: this.selectedAlias,
        reason: reason,
      };
      this.certificateService.invalidateCertificate(revokedCertificateDTO)
        .subscribe((response) => {
          this.snackBarService.openSnackBar(response.body as string);
        })
    }
  }

  openModal() {
    if (this.selectedAlias !== this.invalidAlias) {
      this.dialog.open(CertificateDialogComponent, {
        width: '35%',
        data: this.selectedCertificates
      });
    } else {
      this.snackBarService.openSnackBar("Certificate not selected!");
    }
  }

  openModalInvalidateCert() {
    if (this.selectedAlias !== this.invalidAlias) {
      this.dialog.open(InvalidateCertificateDialogComponent, {
        width: '45%',
        data: this.selectedAlias
      });
    } else {
      this.snackBarService.openSnackBar("Certificate not selected!");
    }
  }
}

<div style="margin-left: 5%; margin-top: 2%;">
  <mat-form-field appearance="fill">
    <mat-label>Select certificate</mat-label>
    <mat-select [(value)]="selectedAlias">
      <mat-option (click)="changeAlias()" *ngFor="let aliase of aliases" [value]="aliase">{{aliase}}</mat-option>
    </mat-select>
  </mat-form-field>
  <button (click)="openModal()" mat-button color="primary">Open certificate</button>
  <button (click)="openModalInvalidateCert()" mat-button color="accent">Invalidate certificate</button>
  <button (click)="checkCertificate()" mat-button color="warn">Check certificate</button>
</div>

// admin-front/admin-app/src/views/AllCertificatesView.vue
<template>
  <div>
    <DropdownComponent
      @changeItem="changeAlias"
      :items="aliases"
    ></DropdownComponent>
    <CertificateDialog ref="dialog1" :certificates="selectedCertificates">
    </CertificateDialog>
    <InvalidateCertificateDialog
      ref="dialog2"
      @closed="invalidateCertificate"
    ></InvalidateCertificateDialog>
    <el-button class="command-button" @click="openModalInvalidateCert"
      >Invalidate certificate</el-button
    >
    <el-button class="command-button" @click="openModal"
      >Open certificate</el-button
    >
    <el-button class="command-button" @click="checkCertificate"
      >Check certificate</el-button
    >
  </div>
</template>

<script>
import CertificateDialog from "../components/CertificateDialog.vue";
import InvalidateCertificateDialog from "../components/InvalidateCertificateDialog.vue";
import DropdownComponent from "../components/DropdownComponent.vue";
import CertificateService from "../service/CertificateService";
export default {
  components: {
    DropdownComponent,
    CertificateDialog,
    InvalidateCertificateDialog,
  },
  data: function () {
    return {
      aliases: [],
      invalidAlias: "----------",
      selectedAlias: "----------",
      selectedCertificates: {},
      showModal: false,
    };
  },
  mounted: function () {
    CertificateService.getAliases().then((response) => {
      this.aliases = [this.invalidAlias];
      this.aliases = [...this.aliases, ...response.data];
    });
  },
  methods: {
    changeAlias: function (alias) {
      this.selectedAlias = alias;
      CertificateService.getCertificate(this.selectedAlias).then((response) => {
        this.selectedCertificates = response.data;
      });
    },
    openModal: function () {
      if (this.selectedAlias !== this.invalidAlias)
        this.$refs.dialog1.openModal();
      else
        this.$toasted.show("Certificate not selected!", {
          theme: "toasted-primary",
          position: "top-center",
          duration: 1700,
        });
    },
    openModalInvalidateCert: function () {
      if (this.selectedAlias !== this.invalidAlias)
        this.$refs.dialog2.openModal();
      else
        this.$toasted.show("Certificate not selected!", {
          theme: "toasted-primary",
          position: "top-center",
          duration: 1700,
        });
    },
    checkCertificate: function () {
      if (this.selectedAlias === this.invalidAlias)
        this.$toasted.show("Certificate not selected!", {
          theme: "toasted-primary",
          position: "top-center",
          duration: 1700,
        });
      else
        CertificateService.checkCertificate(this.selectedAlias)
          .then((response) => {
            this.$toasted.show(response.data, {
              theme: "toasted-primary",
              position: "top-center",
              duration: 3000,
            });
          })
          .catch((response) => console.log(response.data));
    },
    invalidateCertificate(reason) {
      if (this.selectedAlias === this.invalidAlias)
        this.$toasted.show("Certificate not selected!", {
          theme: "toasted-primary",
          position: "top-center",
          duration: 1700,
        });
      else {
        let revokedCertificateDTO = {
          alias: this.selectedAlias,
          reason: reason,
        };
        CertificateService.invalidateCertificate(revokedCertificateDTO).then(
          (response) => {
            this.$toasted.show(response.data, {
              theme: "toasted-primary",
              position: "top-center",
              duration: 3000,
            });
          }
        );
      }
    },
  },
};
</script>

<style scoped>
.command-button {
  margin-top: 1%;
  background-color: rgb(22, 117, 90);
  color: white;
}

.command-button:hover {
  background-color: rgb(146, 142, 142);
  color: rgb(0, 0, 0);
}
</style>
