// admin-front/admin-app/src/components/ExtendedKeyUsageComponent.vue
<template>
  <div class="row">
    <h4 id="title-label">Extended Key usage</h4>
    <div class="col-4">
      <form>
        <vue-form-generator
          :schema="schema1"
          :model="model"
          :options="formOptions"
        >
        </vue-form-generator>
      </form>
    </div>
    <div class="col-4">
      <form>
        <vue-form-generator
          :schema="schema2"
          :model="model"
          :options="formOptions"
        >
        </vue-form-generator>
      </form>
    </div>
    <div class="col-4">
      <form>
        <vue-form-generator
          :schema="schema3"
          :model="model"
          :options="formOptions"
        >
        </vue-form-generator>
      </form>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      model: {
        adobePdfSigning: true,
        documentSigning: true,
        ipSecurityEndSystem: false,
        ocspSigning: false,
        tlsWebClientAuthentication: false,
        timeStamping: false,
        tlsWebServerAuthentication: false,
        emailProtection: false,
        tslSigning: false,
      },

      schema1: {
        groups: [
          {
            fields: [
              {
                type: "checkbox",
                label: "Adobe Pdf Signing",
                model: "adobePdfSigning",
              },
              {
                type: "checkbox",
                label: "Document Signing",
                model: "documentSigning",
              },
              {
                type: "checkbox",
                label: "Ip Security End System",
                model: "ipSecurityEndSystem",
              },
            ],
          },
        ],
      },
      schema2: {
        groups: [
          {
            fields: [
              {
                type: "checkbox",
                label: "Ocsp Signing",
                model: "ocspSigning",
              },
              {
                type: "checkbox",
                label: "Tls Web Client Authentication",
                model: "tlsWebClientAuthentication",
              },
              {
                type: "checkbox",
                label: "Time stamping",
                model: "timeStamping",
              },
            ],
          },
        ],
      },
      schema3: {
        groups: [
          {
            fields: [
              {
                type: "checkbox",
                label: "Tls Web Server Authentication",
                model: "tlsWebServerAuthentication",
              },
              {
                type: "checkbox",
                label: "Email Protection",
                model: "emailProtection",
              },
              {
                type: "checkbox",
                label: "Tsl Signing",
                model: "tslSigning",
              },
            ],
          },
        ],
      },
      formOptions: {
        validateAfterLoad: false,
        validateAfterChanged: true,
        validateAsync: true,
      },
    };
  },
};
</script>

// admin-front/admin-app/src/app/components/extended-key-usage/extended-key-usage.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { ExtendedKeyUsageDTO } from 'src/app/models/ExtendedKeyUsageDTO';

@Component({
  selector: 'app-extended-key-usage',
  templateUrl: './extended-key-usage.component.html',
  styleUrls: ['./extended-key-usage.component.scss']
})
export class ExtendedKeyUsageComponent implements OnInit {

  @Input()
  extendedKeyUsage!: ExtendedKeyUsageDTO;

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="container center">
    <h4>Extended key usage</h4>

    <div class="row">
        <div class="col">
            <input [(ngModel)]="extendedKeyUsage.adobePdfSigning" class="form-check-input" type="checkbox" value="" id="adobePdfSigning">
            <label class="form-check-label" for="adobePdfSigning">
                Adobe pdf signing
            </label>
        </div>
        <div class="col">
            <input [(ngModel)]="extendedKeyUsage.documentSigning" class="form-check-input" type="checkbox" value="" id="documentSigning">
            <label class="form-check-label" for="documentSigning">
                Document Signing
            </label>
        </div>
        <div class="col">
            <input [(ngModel)]="extendedKeyUsage.ipSecurityEndSystem" class="form-check-input" type="checkbox" value="" id="ipSecurityEndSystem">
            <label class="form-check-label" for="ipSecurityEndSystem">
                Ip security end system
            </label>
        </div>
    </div>
    
    <div class="row">
        <div class="col">
            <input [(ngModel)]="extendedKeyUsage.ocspSigning" class="form-check-input" type="checkbox" value="" id="ocspSigning">
            <label class="form-check-label" for="ocspSigning">
                Ocsp signing
            </label>
        </div>
        <div class="col">
            <input [(ngModel)]="extendedKeyUsage.tlsWebClientAuthentication" class="form-check-input" type="checkbox" value="" id="tlsWebClientAuthentication">
            <label class="form-check-label" for="tlsWebClientAuthentication">
                Tls web client authentication
            </label>
        </div>
        <div class="col">
            <input [(ngModel)]="extendedKeyUsage.timeStamping" class="form-check-input" type="checkbox" value="" id="timeStamping">
            <label class="form-check-label" for="timeStamping">
                Time stamping
            </label>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <input [(ngModel)]="extendedKeyUsage.tlsWebServerAuthentication" class="form-check-input" type="checkbox" value="" id="tlsWebServerAuthentication">
            <label class="form-check-label" for="tlsWebServerAuthentication">
                Tls web server authentication
            </label>
        </div>
        <div class="col">
            <input [(ngModel)]="extendedKeyUsage.emailProtection" class="form-check-input" type="checkbox" value="" id="emailProtection">
            <label class="form-check-label" for="emailProtection">
                Email protection 
            </label>
        </div>
        <div class="col">
            <input [(ngModel)]="extendedKeyUsage.tslSigning" class="form-check-input" type="checkbox" value="" id="tslSigning">
            <label class="form-check-label" for="tslSigning">
                Tsl signing
            </label>
        </div>
    </div>
</div>
